- name: taking uname and password
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      promt: pls enter your user name
      private: false
  
    - name: password
      promt: pls enter your password
      private: false
  tasks: 
  - name: printing var from user
    ansible.builtin.debug:
      msg: "uname is: {{ username }}, password is: {{ password }}"