- name: taking uname and password
  hosts: localhost
  connection: local

  vars_prompt:
    - name: username
      prompt: "please enter your user name"
      private: false

    - name: password
      prompt: "please enter your password"
      private: false

  tasks:
  - name: printing var from user
    ansible.builtin.debug:
      msg: "uname is: {{ username }}, password is: {{ password }}"
