- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: "Ansible from play"
  vars_files:
  - deatils.yaml
  vars_prompt:
  - name: NAME
    prompt: Enter the name
    private: false
  
  tasks:
    - name: print name
      vars:
      NAME: "Ansible from task"
      ansible.builtin.debug:
        msg: "Hi {{ NAME }}"
