- name: demo on loops
  hosts: local
  connection: local
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - ramesh
        - suresh
        - Sravan