- name: demo on filters
  hosts: local
  connection: local
  vars:
    tagsmap:
      name: sravan Kumar
      designation: junior devops engineer
      company: processq inc
    tagslist: [
        {
            "key": "name",
            "value": "sravan Kumar"
        },
        {
            "key": "designation",
            "value": "junior devops engineer"
        },
        {
            "key": "company",
            "value": "processq inc"
        }
    ]
  
  tasks:
    - name: converting map to list
      ansible.builtin.debug:
        msg: "{{ tagsmap | dict2items }}"

  tasks:
    - name: converting list to map
      ansible.builtin.debug:
        msg: "{{ tagslist | items2dict }}"